### obtener lista de sopas por paginacion
GET http://localhost:8080/api/v1/menu/soups?pageSize=2&pageNumber=2
### Obtner lista de platos principales con paginacion
GET http://localhost:8080/api/v1/menu/mains/?pageSize=2&pageNumber=0
### obtener lista de platos principales con paginacion
GET http://localhost:8080/api/v1/menu/desserts/?pageSize=2&pageNumber=0
### obtener lista de categorias
GET http://localhost:8080/api/v1/menu/categories