### post para registrar un nuevo pedido
POST http://localhost:8080/api/v1/order/
Accept: application/json
Content-Type: application/json

{
  "clientId": 16,
  "sucursalId": 1,
  "direccion": {
    "id": 1,
    "direccion": "Av 20 de octubre #1540",
    "latitud": -16.6584,
    "longitud": -66.6584,
    "detalle": "Casa naranja"
  },
  "tarjeta": {
    "id": 1,
    "nro": "478465456",
    "vencimiento": "11/22",
    "nombre": "arimonmon"
  },
  "metodoDePago": 2,
  "metodoDeEntrega": 1,
  "estado": 1,
  "total": 150,
  "propina": 10,
  "platos": [
    {
      "id": 10,
      "cantidad": 2,
      "nota": "sin pollo"
    },
    {
      "id": 11,
      "cantidad": 3,
      "nota": "sin nada nadita de pollo"
    }
  ,
    {
      "id": 12,
      "cantidad": 4,
      "nota": "con mucho pollo"
    }
  ]
  }

### Get para recuperar orden por id
GET  http://localhost:8080/api/v1/order/54
Accept: application/json
Content-Type: application/json

###PUt para editar estado de los pedidos

PUT http://localhost:8080/api/v1/order/54
Accept: application/json
Content-Type: application/json

{
  "estado": 2
}