###

GET http://localhost:8080/api/v1/plate/2
Accept: application/json

###

POST http://localhost:8080/api/v1/plate/
Accept: application/json
Content-Type: application/json

{
  "nombre": "Pie de Manzana",
  "precio": 15.00,
  "descripcion": "al de texto aqui",
  "imagen": "https://mccormick.widen.net/content/5pgmsri5uh/png/Pie%20de%20Manzana.png?crop=true&anchor=341,0&color=ffffff00&u=u0bb0o&w=1365&h=1365%27",
  "categoria": "3"
}

###

PUT http://localhost:8080/api/v1/plate/9
Accept: application/json
Content-Type: application/json

{
  "nombre": "Pie de Manzana",
  "precio": 30.00,
  "descripcion": "al de texto aqui",
  "imagen": "https://mccormick.widen.net/content/5pgmsri5uh/png/Pie%20de%20Manzana.png?crop=true&anchor=341,0&color=ffffff00&u=u0bb0o&w=1365&h=1365%27",
  "categoria": "3"
}

###

DELETE http://localhost:8080/api/v1/plate/13
Accept: application/json
Content-Type: application/json

{
  "status": 0
}

###

GET http://localhost:8080/api/v1/plate/?category=1